"""
JWT Authentication Utilities for Python FastAPI Services
Shared JWT configuration that must match Spring Boot and NestJS services
"""
import os
from typing import Optional, Dict, Any
from jose import JWTError, jwt
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials

# JWT Configuration - MUST match Spring Boot and NestJS services
JWT_SECRET = os.getenv("JWT_SECRET", "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970")
JWT_ALGORITHM = "HS256"

# HTTP Bearer token security
security = HTTPBearer()


def verify_token(credentials: HTTPAuthorizationCredentials = Depends(security)) -> Dict[str, Any]:
    """
    Verify JWT token and return payload
    
    This validates tokens generated by any microservice in the ecosystem
    using the shared JWT secret.
    
    Args:
        credentials: HTTP Authorization credentials containing the Bearer token
        
    Returns:
        dict: Decoded JWT payload containing user information
        
    Raises:
        HTTPException: If token is invalid or expired
    """
    try:
        token = credentials.credentials
        payload = jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
        
        # Validate required fields exist in payload
        if not payload.get("sub"):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Token missing required claims",
                headers={"WWW-Authenticate": "Bearer"},
            )
        
        return payload
    except JWTError as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid authentication credentials: {str(e)}",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication failed",
            headers={"WWW-Authenticate": "Bearer"},
        )


def get_current_user_id(token_payload: Dict[str, Any] = Depends(verify_token)) -> str:
    """
    Extract user ID from verified token payload
    
    Args:
        token_payload: Decoded JWT payload
        
    Returns:
        str: User ID from the token
    """
    return token_payload.get("sub")


def get_current_user_roles(token_payload: Dict[str, Any] = Depends(verify_token)) -> list:
    """
    Extract user roles from verified token payload
    
    Args:
        token_payload: Decoded JWT payload
        
    Returns:
        list: User roles from the token
    """
    return token_payload.get("roles", [])
