import { Injectable, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PassportStrategy } from '@nestjs/passport';
import { ExtractJwt, Strategy } from 'passport-jwt';

/**
 * JWT Authentication Strategy
 * Validates JWT tokens generated by any microservice in the ecosystem
 * using the shared JWT secret
 */
@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy) {
    constructor(private configService: ConfigService) {
        super({
            jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
            ignoreExpiration: false,
            secretOrKey: configService.get<string>('jwt.secret'),
        });
    }

    /**
     * Validates JWT token payload
     * This method is called after the token signature is verified
     * @param payload - The decoded JWT payload
     * @returns The user information extracted from the token
     */
    async validate(payload: any) {
        if (!payload) {
            throw new UnauthorizedException('Invalid token payload');
        }

        // Return user information from token
        // The payload structure should match what's generated by User-Management service
        return {
            userId: payload.sub,
            username: payload.username,
            email: payload.email,
            roles: payload.roles || [],
        };
    }
}
